canvas_width: 1200
canvas_height: 750
sidebar_width: 60
video_width: 640
video_height: 512
offset: 50
fps: 24
working_directory : 
images_directory: 
method: part # part or entire 
sample_stride: 2 # part: 1, entire: 2
face_swap: True
frame_interpolation: True
num_frame: 6

s3it:
  username: '' # S3IT account username
  password: '' # S3IT account password

